# Generated by Django 3.1.5 on 2021-02-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0018_auto_20210129_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='safety_guide_accept_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_account',
            name='term_condition_accept_state',
            field=models.BooleanField(default=False),
        ),
    ]
