# Generated by Django 3.1.5 on 2021-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0019_auto_20210222_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerecord',
            name='sample_survey',
            field=models.JSONField(null=True),
        ),
    ]
