# Generated by Django 3.1.5 on 2021-03-03 18:35

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0020_samplerecord_sample_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerecord',
            name='sample_survey',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
