# Generated by Django 3.1.5 on 2021-03-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0021_auto_20210303_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInsectUserUpload',
            fields=[
                ('insect_id', models.AutoField(primary_key=True, serialize=False)),
                ('insect_image_path', models.ImageField(null=True, upload_to='user-insect-img')),
            ],
        ),
        migrations.CreateModel(
            name='RiverEnvironmentImage',
            fields=[
                ('river_id', models.AutoField(primary_key=True, serialize=False)),
                ('river_image_path', models.ImageField(null=True, upload_to='river-environment-img')),
            ],
        ),
    ]
