# Generated by Django 3.1.5 on 2021-03-10 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aquality_server', '0022_allinsectuserupload_riverenvironmentimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_Account',
            new_name='LoginAccount',
        ),
        migrations.RenameModel(
            old_name='User_Account',
            new_name='UserAccount',
        ),
    ]
