# Generated by Django 3.1.5 on 2021-03-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0023_auto_20210310_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinsectuserupload',
            name='sample_record_data',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='aquality_server.samplerecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riverenvironmentimage',
            name='sample_record_data',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='aquality_server.samplerecord'),
            preserve_default=False,
        ),
    ]
