# Generated by Django 3.1.5 on 2021-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0024_auto_20210310_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblemRecord',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_image_path', models.ImageField(null=True, upload_to='report-insect-img')),
                ('report_problem', models.CharField(max_length=200)),
                ('report_problem_description', models.TextField()),
            ],
        ),
    ]
