# Generated by Django 3.1.5 on 2021-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0025_reportproblemrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAccount',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='ph',
            new_name='pH',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ecological_status',
        ),
        migrations.RemoveField(
            model_name='data',
            name='river',
        ),
        migrations.RemoveField(
            model_name='data',
            name='score_by_insect',
        ),
        migrations.RemoveField(
            model_name='samplerecord',
            name='sample_ph',
        ),
        migrations.AddField(
            model_name='samplerecord',
            name='sample_pH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='samplerecord',
            name='sample_tmp',
            field=models.FloatField(null=True),
        ),
    ]
