# Generated by Django 3.1.5 on 2021-03-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0026_auto_20210316_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allinsectuserupload',
            old_name='insect_id',
            new_name='all_insect_image_id',
        ),
        migrations.RenameField(
            model_name='riverenvironmentimage',
            old_name='river_id',
            new_name='river_environment_image_id',
        ),
    ]
