# Generated by Django 3.1.5 on 2021-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0027_auto_20210318_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinsectuserupload',
            name='insect_image_path',
            field=models.ImageField(default=None, max_length=900000, null=True, upload_to='user-insect-img'),
        ),
        migrations.AlterField(
            model_name='riverenvironmentimage',
            name='river_image_path',
            field=models.ImageField(default=None, max_length=900000, null=True, upload_to='river-environment-img'),
        ),
    ]
