# Generated by Django 3.1.5 on 2021-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0029_auto_20210322_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerecord',
            name='sample_coor_lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='samplerecord',
            name='sample_coor_lng',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='samplerecord',
            name='sample_weather',
            field=models.JSONField(null=True),
        ),
    ]
