# Generated by Django 3.1.5 on 2021-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquality_server', '0030_auto_20210404_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_time_login',
            field=models.BooleanField(default=False),
        ),
    ]
