name: Internal release

on:
  push:
    branches:
      - 15998_Generate_release_apk_file
      # - release/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: set android/gradle.properties
        run: |
          cd mobile_ui/android/
          echo $GRADLE_PROPERTIES | tr ' ' '\n' >> gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash

      - name: set RELEASE KEYSTORE
        run: |
          cd mobile_ui/android/app
          echo $SIGNING_KEY | tr ' ' '\n' > my-release-key.keystore.b64
          base64 -d my-release-key.keystore.b64 > my-release-key.keystore
        env:
          SIGNING_KEY: ${{ secrets.BASE64_RELEASE_SIGNING_KEY }}
        shell: bash

      - name: add system limit for number of file
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

      - name: Build Release Sign AAB
        run: |
          cd mobile_ui
          npm i
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease

      - name: Upload bundle release aab Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: mobile_ui/android/app/build/outputs/bundle/release/app-release.aab

  upload_to_test_track:
    name: Uploading build to Internal test track
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle

      - name: Uploading to test track
        uses: r0adkll/upload-google-play@v1
        with:
          # Your service account JSON GitHub secret
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          # Your package name
          packageName: 'com.cccmi.aquality'
          releaseFiles: app-release.aab
          track: internal
