name: Django CI Workflow

on:
  pull_request:
    branches:
      - AqualityServer_Master
  push:
    branches:
      - AqualityServer_Master

# three job definition
jobs:
  Django-check-job: # health check job for testing and code formatting check
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
        with:
          ref: server
      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # if you want multiple python version run just use matrix strategy in job config. See the documentation of GitHub Actions
      - name: Check Python version # checking the python version to see if 3.x is installed.
        run: python --version
      - name: Install requirements # install application requirements
        run: |
          cd Aquality2
          pip install -r requirements.txt

      - name: create .env file
        run: |
          cd Aquality2
          touch .env
          echo $DEV_ENV_FILE | tr ' ' '\n' >> .env
          cat .env
        env:
          DEV_ENV_FILE: ${{ secrets.SERVER_ENV }}
        shell: bash

      - name: Run Migrations # run migrations to create table in side car db container
        run: |
          cd Aquality2
          python manage.py migrate

      - name: Run Test # running tests
        run: |
          cd Aquality2  
          python manage.py test
