name: Deploy Aquality Server
on:
  push:
    branches:
    - AqualityServer_Master
  pull_request:
    branches:
    - AqualityServer_Master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: AqualityServer_Master

    - name: create .env file
      run: |
          cd Aquality_Two_Backend_Server
          touch .env
          echo $DEV_ENV_FILE | tr ' ' '\n' >> .env
          cat .env
      env:
        DEV_ENV_FILE: ${{ secrets.SERVER_ENV }}
      shell: bash

    - name: checkout to folder
      run: |
          echo "export PATH=\'/home/runner/.local/bin:\$PATH\'" >> ~/.bashrc && source ~/.bashrc
          cd Aquality_Two_Backend_Server
          sudo apt-get update -y
          pip3 install --upgrade pip awsebcli
          eb deploy
      shell: bash